### PR TITLE
Fix `tileconv` paths for Linux & Mac

### PR DESCRIPTION
**Pull request by Ineth2**
The mod uses `HANDLE_TILECONV`, which in turn checks for the `tileconv`
executable in a subfolder named after the content of the `%WEIDU_OS%`
variable.

That variable holds `osx` and `unix`, respectively, on Mac and Linux -
not `macosx` and `linux`. See:
http://www.weidu.org/~thebigg/README-WeiDU.html#WEIDU_OS

This commit renames those two subfolders accordingly.

I've tested it on Linux and confirmed that without this commit,
installation of the main component fails with:

    ERROR: "tileconv" does not exist at "ToA/tools/tileconv/unix/x86_64/tileconv"

whereas after this commit, the installation succeeds.

### CODE REVIEW

**Comment by RoxanneSHS** [comment]
Are you aware that this is just a fork of the original mod which is here https://github.com/whiteagnus/ToA?

I can include your commit into my fork, so we have all the corrections in one place since the original mod seems to be abandoned. Maybe at some stage this replaces the master in e.g. BWS?

**Comment by Ineth2** [comment]
Ah, I didn't check the download URL used by BWS and thought this was it.

Should this fix be added to the Fixpack as a `_rename` action, then?

**Comment by RoxanneSHS** [comment]
For the moment yes.
Maybe if there are more corrections and the main branch stays dead we one day switch to the updated version with BWS. But not yet.

**Comment by Ineth2** [comment]
I tried to convert it to a Fixpack patch, but it looks like the `_rename` mechanism doesn't work with directories... :(

**Comment by RoxanneSHS** [comment]
The BWS now points to the forked (corrected) download, as does the EET compatible mod list. 

There is no way to influence the BWP and old game, but there may not be too many linux/mac users there, at least there was no complaint for the last decade from that fraction.

**Pull request merged**
